# https://travis-ci.com/marmelab/awale-python/

language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  python3 -m unittest discover

branches:
  only:
    - master
